
//recuperation des customers
GET http://127.0.0.1:8000/api/clients
Authorization:Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE1OTc3NTQ5MzEsImV4cCI6MTU5Nzc1ODUzMSwicm9sZXMiOlsiUk9MRV9VU0VSIl0sInVzZXJuYW1lIjoiam9oYW4ub3JlaWxseUB3aXR0aW5nLm9yZyJ9.r6gLqkr6dmY5gsjAakGykyNModvlKCTzvbT1UjeRcfUIMZgquQCfvSyzBY76NKn7JVymdPxptLLkJ-h6pkgWAQgTcH-pSTOcDSxx-27kGnyN_WCfpTVTAg03LUO_F-KTWMSfncf-8L3ysOfS2_sfEWZNcGkDqc9nH8EjsUXi2Epo2_4aFPLGck3BcNAEg7ImcfsdvJ1JSJuhih5B9qoQsQqVC7MkgC7iZ8ya4TmchOOCpyzPPvppV-yueM2-ZyJaz9MAuBOC4cX2bnq7iDxl68-TJQ87wtdrjDyP8caVxgo3W9OzPDvCnHUFM3DaFNn8ySMQ1Gxiza84XNKDCcA7LyKsbRqVlY8cXMFbRKQarIvKH3ppZdx6f00NZl_99ewdRO1eoeNJgKUaG7pXXt0FAjNyk-0dReTAlE1Xuf8C-auSSRt6bJN_O4vYidTuo1K_jM7sFjcz4zy2m0EFDZJS2llJods0rviBtqRsF5fr9EM7xJBCi1L55I6o_02NetdA2QYf7koTgeZ7_MP5ihIDix59iAlk9-kTyhm66U0yjh4QYvPYMfKvt9vbxhLN2MevBlzte1ikwrZt9UXt-AaNE1pn1-WwkTyyn7xySzWyFJxYJDwalr-DpJ6-Jx9B4TPOsREL9Y5e6Tyksc1t9_52Zc_neC2OXLSOUoHRUdVgzkw

###

//recuperation des invoices d'un customer grace au subresource
GET http://127.0.0.1:8000/api/client/317/factures
Authorization:Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE1OTc3NTQ5MzEsImV4cCI6MTU5Nzc1ODUzMSwicm9sZXMiOlsiUk9MRV9VU0VSIl0sInVzZXJuYW1lIjoiam9oYW4ub3JlaWxseUB3aXR0aW5nLm9yZyJ9.r6gLqkr6dmY5gsjAakGykyNModvlKCTzvbT1UjeRcfUIMZgquQCfvSyzBY76NKn7JVymdPxptLLkJ-h6pkgWAQgTcH-pSTOcDSxx-27kGnyN_WCfpTVTAg03LUO_F-KTWMSfncf-8L3ysOfS2_sfEWZNcGkDqc9nH8EjsUXi2Epo2_4aFPLGck3BcNAEg7ImcfsdvJ1JSJuhih5B9qoQsQqVC7MkgC7iZ8ya4TmchOOCpyzPPvppV-yueM2-ZyJaz9MAuBOC4cX2bnq7iDxl68-TJQ87wtdrjDyP8caVxgo3W9OzPDvCnHUFM3DaFNn8ySMQ1Gxiza84XNKDCcA7LyKsbRqVlY8cXMFbRKQarIvKH3ppZdx6f00NZl_99ewdRO1eoeNJgKUaG7pXXt0FAjNyk-0dReTAlE1Xuf8C-auSSRt6bJN_O4vYidTuo1K_jM7sFjcz4zy2m0EFDZJS2llJods0rviBtqRsF5fr9EM7xJBCi1L55I6o_02NetdA2QYf7koTgeZ7_MP5ihIDix59iAlk9-kTyhm66U0yjh4QYvPYMfKvt9vbxhLN2MevBlzte1ikwrZt9UXt-AaNE1pn1-WwkTyyn7xySzWyFJxYJDwalr-DpJ6-Jx9B4TPOsREL9Y5e6Tyksc1t9_52Zc_neC2OXLSOUoHRUdVgzkw


###

//incremente le chrono d'une fature
POST http://127.0.0.1:8000/api/invoices/1621/increment
content-type: application/json

{

}

###

//recuperation des customers plus filtre fistName choix de strategy end, exact,partial ex....
GET http://127.0.0.1:8000/api/clients?firstName=Fr&LastName=Reichel

###

//recuperation des customers + demande de pagi + nbr d'items
GET http://127.0.0.1:8000/api/customers?pagination=true&itemsPerPage=10

###

//recuperation des facture 
GET http://127.0.0.1:8000/api/invoices

###

//recuperation des facture pas de pagination
GET http://127.0.0.1:8000/api/invoices?pagination=false

###

//recuperation des facture pas de pagination + order
GET http://127.0.0.1:8000/api/invoices?order[amount]=desc

###

//creation d'un customer
POST http://127.0.0.1:8000/api/clients
content-type: application/json
Authorization:Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE1OTc3NTk1MzcsImV4cCI6MTU5Nzc2MzEzNywicm9sZXMiOlsiUk9MRV9VU0VSIl0sInVzZXJuYW1lIjoiam9oYW4ub3JlaWxseUB3aXR0aW5nLm9yZyJ9.l0UQaLewxFstX_aZbsXD4CavCzva8u1R52Vw5wcZ34Y-mjPVIk0sbeYCVhHg5ze1a9UHLlT7kmVAXHJzYSMT4oL5sb7J-YytyC1f5lQWOrAYF0LGTwbLh7me4tUZPzoPAfgaezwZxwYWytfi81LvKftkKaYr8pO6ucRaJk5gMiX26wMX4HACBg4wkHJVvprOO54h9Sp30uHyId7sXiRqs0i_WhPTlbE2aEXpRXGa-u-1hnYAhWBHQrxN2eZ0GH_4Njk0p6J3pQw15pcRRei2xPC7eH9_DUdOgWaoia_3G3gT8tLuqQHudfQev_PnqeqUvoHt_xG5EVgWNVJOe-w64rMirMTJvYGTaQRsLPKvDDYOXXoXeRcmXvDZsUFThwDMBh1y91vy1NHnWPx-fg16LN3CV9gfa0l2ye-mmRpNP3hf1GJ9MIP_E8LH7lo_O-aPCnJ-udBCrBamBltemnOXdm2SBF2WGag1pZT9KzZFhsJ_-AFHePIMxqNTidnz2CNhrC9FtsWlnDFY8m6OnuYXIlEthTn420qhOYrt3kKWvVHNWQOWTtvbpBJ9IXEUixCBfkNgIIh4aCxv-RcqzmIC4E_3hiVGWOZh94GyOhi5gONpT-i7qxu3npH2EJhYZMv3DWOLQ_wRkyM2JWZ3aDyk6vSAXXDTTXcgC900l5B6Nes


{
    "firstName":"teeeegdf",
    "lastName":"lfghfghg",
    "email":"totool@astdgficot.fr"
}

###

//creation d'une factures
POST http://127.0.0.1:8000/api/invoices
content-type: application/json

{
    "amount":500,
    "chrono":34,
    "status":"PAID",
    "sentAt":"2019-12-05",
    "customer":"\/api\/client\/314"
}


###

//creation d'un utilisateur
POST http://127.0.0.1:8000/api/users
content-type: application/json

{
    "firstName":"nicoff",
    "lastName":"riotd",
    "email":"nico.rifgot@freef.fr",
    "password":"pass"
}

###

//tester le login avec jwt
POST http://127.0.0.1:8000/api/login_check
content-type: application/json

{
    "username":"johan.oreilly@witting.org",
    "password":"pass"
}
