
//recuperation des customers
GET http://127.0.0.1:8000/api/clients

###

//recuperation des invoices d'un customer grace au subresource
GET http://127.0.0.1:8000/api/client/317/factures

###

//incremente le chrono d'une fature
POST http://127.0.0.1:8000/api/invoices/1621/increment
content-type: application/json

{

}

###

//recuperation des customers plus filtre fistName choix de strategy end, exact,partial ex....
GET http://127.0.0.1:8000/api/clients?firstName=Fr&LastName=Reichel

###

//recuperation des customers + demande de pagi + nbr d'items
GET http://127.0.0.1:8000/api/customers?pagination=true&itemsPerPage=10

###

//recuperation des facture 
GET http://127.0.0.1:8000/api/invoices

###

//recuperation des facture pas de pagination
GET http://127.0.0.1:8000/api/invoices?pagination=false

###

//recuperation des facture pas de pagination + order
GET http://127.0.0.1:8000/api/invoices?order[amount]=desc

###

//creation d'un customer
POST http://127.0.0.1:8000/api/clients
content-type: application/json

{
    "firstName":"teeee",
    "lastName":"lfghfhg",
    "email":"totool@asticot.fr",
    "user":"\/api\/users\/31"
}

###

//creation d'une factures
POST http://127.0.0.1:8000/api/invoices
content-type: application/json

{
    "amount":500,
    "chrono":34,
    "status":"PAID",
    "sentAt":"2019-12-05",
    "customer":"\/api\/client\/314"
}


###

//creation d'un utilisateur
POST http://127.0.0.1:8000/api/users
content-type: application/json

{
    "firstName":"nico",
    "lastName":"riot",
    "email":"nico.riot@free.fr",
    "password":"pass"
}
