
//recuperation des customers
GET https://127.0.0.1:8000/api/customers

###

//recuperation des customers plus filtre fistName choix de strategy end, exact,partial ex....
GET https://127.0.0.1:8000/api/customers?firstName=Fr&LastName=Reichel

###

//recuperation des customers + demande de pagi + nbr d'items
GET https://127.0.0.1:8000/api/customers?pagination=true&itemsPerPage=10

###

//recuperation des facture 
GET https://127.0.0.1:8000/api/invoices

###

//recuperation des facture pas de pagination
GET https://127.0.0.1:8000/api/invoices?pagination=false

###

//recuperation des facture pas de pagination + order
GET https://127.0.0.1:8000/api/invoices?order[amount]=desc